video:
    video_path: ./videos/sea_turtle_832.mp4
    source_prompt: A graceful sea turtle is swimming through the current, moving its flippers rhythmically.
    target_prompt: A graceful seal is swimming through the current, moving its flippers rhythmically.
    source_blend: sea turtle
    target_blend: seal

infernece:
    num_inference_step: 50

training-free-type:
    flag_flowedit: False
    flag_flowalign: True

flowedit:
    strength: 0.7
    target_guidance_scale: 13.5
    source_guidance_scale: 5.0
    save_video: ./wanedit_turtle_2_seal.mp4

flowalign:
    strength: 0.7
    target_guidance_scale: 19.5
    flag_attnmask: False
    zeta_scale: 1e-3
    bg_zeta_scale: 1e-3
    save_video: ./wanalign_turtle_2_seal.mp4